name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  setup:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Compose
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "./docker-compose.yml"
    - name: Build and run Docker Compose Service
      run: docker-compose up -d

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Add sqlx
      run: cargo install sqlx-cli --no-default-features --features postgres
    - name: Build
      run: cargo build --verbose
  tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Database migration
      run: sqlx db create; sqlx migrate run
    - name: Run tests
      run: cargo test --verbose
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  cleanup:
    needs: tests
    runs-on: ubuntu-latest     

    steps:
    - name: Shut down Docker Compose services
      run: docker-compose down
