name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    # Setup Docker Compose
    - uses: actions/checkout@v3
    - name: Set up Docker Compose
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "./docker-compose.yml"
    - name: Build and run Docker Compose Service
      run: docker-compose up -d
    # Setup Rust (using database)
    - name: Add sqlx
      run: cargo install sqlx-cli --no-default-features --features postgres
    - name: Database migration
      run: sqlx db create; sqlx migrate run
    # Build and test
    - name: Build
      run: cargo build --verbose
    - name: setup grcov
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --verbose --no-fail-fast
      env:
        CARGO_INCREMENTAL: '0'
        RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
        RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
    # Report coverage from Codecov
    - name: rust-grcov
      uses: actions-rs/grcov@v0.1.5
    - name: Codecov report
      uses: codecov/codecov-action@v3.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    # Shut down Docker Compose (Clean up)
    - name: Shut down Docker Compose services
      run: docker-compose down
