name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Compose
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "./docker-compose.yml"
    - name: Build and run Docker Compose Service
      run: docker-compose up -d
    - name: Add sqlx
      run: cargo install sqlx-cli --no-default-features --features postgres
    - name: Database migration
      run: sqlx db create; sqlx migrate run
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Push to codecov.io
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        cargo install cargo-tarpaulin
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash) -X gcov -t $CODECOV_TOKEN
    - name: Shut down Docker Compose services
      run: docker-compose down
